spring.application.name=UberHaiti

# --- GESTION DU PORT ---
# Render injecte automatiquement le port via la variable PORT.
server.port=${PORT:8080}

# Profil actif
spring.profiles.active=${APP_MODE:dev}

# =========================================================================
# CONFIGURATION HYBRIDE (MYSQL LOCAL / POSTGRESQL AIVEN)
# =========================================================================

# URL : MySQL local par défaut. 
# Sur Render, utilise DB_URL=jdbc:postgresql://pg-21f0dd7a-pg-uber-ouest-christopher.b.aivencloud.com:22088/defaultdb?sslmode=require
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/uber_ouest?useSSL=false&serverTimezone=UTC}

# Utilisateur : root par défaut. Sur Render, utilise DB_USER=avnadmin
spring.datasource.username=${DB_USER:root}

# Mot de passe : Sur Render, utilise DB_PASS=AVNS_-dL22mD7LBhOoK_B3PS
spring.datasource.password=${DB_PASS:49358485}

# Driver : Bascule automatique entre MySQL et PostgreSQL
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# Dialecte Hibernate : Indispensable pour la compatibilité SQL
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}

# Gestion automatique du schéma
spring.jpa.hibernate.ddl-auto=${DB_DDL:update}
spring.jpa.show-sql=true

# =========================================================================
# SÉCURITÉ JWT
# =========================================================================
app.jwt.secret=${JWT_SECRET:UberHaitiOuest2026_SecuriteMaximale_PortAuPrince_Haiti_LongKeyHS512}
app.jwt.expiration=86400000

# Sécurité des erreurs
server.error.include-message=always
server.error.include-stacktrace=never
logging.level.org.springframework.security=DEBUG

# =========================================================================
# CONFIGURATION MONCASH SANDBOX
# =========================================================================
moncash.client.id=4f332baa52f0dc90d3e902e023c44809
moncash.client.secret=hkmk-pur2p3ICiJ-1kcziHXiB9wgdYJQA9dolkoLu-Gm1rawvmdWnvCIdkIyreXT
moncash.api.token=https://sandbox.moncashbutton.digicelgroup.com/Api/oauth/token
moncash.api.payment=https://sandbox.moncashbutton.digicelgroup.com/Api/v1/CreatePayment
moncash.url.redirect=https://sandbox.moncashbutton.digicelgroup.com/IPG/Payment/Pay?token=