spring.application.name=UberHaiti

# --- GESTION DU PORT (Indispensable pour Render) ---
server.port=${PORT:10000}

# Profil actif
spring.profiles.active=prod

# =========================================================================
# CONFIGURATION FULL CLOUD (POSTGRESQL AIVEN)
# =========================================================================

# Connexion directe à Aiven (Fonctionne en local et sur Render)
spring.datasource.url=jdbc:postgresql://pg-21f0dd7a-pg-uber-ouest-christopher.b.aivencloud.com:22088/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_-dL22mD7LBhOoK_B3PS
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecte Hibernate spécifique à PostgreSQL (Crucial pour les Boolean)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Gestion du schéma
# 'update' va tenter d'ajuster les tables existantes automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Correction pour PostgreSQL et les types Hibernate 6
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# =========================================================================
# SÉCURITÉ JWT
# =========================================================================
app.jwt.secret=UberHaitiOuest2026_SecuriteMaximale_PortAuPrince_Haiti_LongKeyHS512
app.jwt.expiration=86400000

# Sécurité des erreurs
server.error.include-message=always
server.error.include-stacktrace=never
logging.level.org.springframework.security=DEBUG

# =========================================================================
# CONFIGURATION MONCASH SANDBOX
# =========================================================================
moncash.client.id=4f332baa52f0dc90d3e902e023c44809
moncash.client.secret=hkmk-pur2p3ICiJ-1kcziHXiB9wgdYJQA9dolkoLu-Gm1rawvmdWnvCIdkIyreXT
moncash.api.token=https://sandbox.moncashbutton.digicelgroup.com/Api/oauth/token
moncash.api.payment=https://sandbox.moncashbutton.digicelgroup.com/Api/v1/CreatePayment
moncash.url.redirect=https://sandbox.moncashbutton.digicelgroup.com/IPG/Payment/Pay?token=
