spring.application.name=UberHaiti

# Gestion du Port (0 pour port aléatoire en local, ou fixé par l'hébergeur)
server.port=${PORT:0}

# Profil actif (défini sur 'dev' par défaut pour le local)
spring.profiles.active=${APP_MODE:dev}

# =========================================================================
# CONFIGURATION DE LA BASE DE DONNÉES (MYSQL)
# =========================================================================
# En local : utilise localhost
# Sur Aiven : il faudra définir la variable d'environnement DB_URL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/uber_ouest?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:49358485}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate & JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${DB_DDL:update}
spring.jpa.show-sql=true

# =========================================================================
# SÉCURITÉ JWT
# =========================================================================
app.jwt.secret=${JWT_SECRET:UberHaitiOuest2026_SecuriteMaximale_PortAuPrince_Haiti_LongKeyHS512}
app.jwt.expiration=86400000

# Sécurité des erreurs
server.error.include-message=always
server.error.include-stacktrace=never
logging.level.org.springframework.security=DEBUG

# =========================================================================
# CONFIGURATION MONCASH SANDBOX
# =========================================================================
moncash.client.id=4f332baa52f0dc90d3e902e023c44809
moncash.client.secret=hkmk-pur2p3ICiJ-1kcziHXiB9wgdYJQA9dolkoLu-Gm1rawvmdWnvCIdkIyreXT
moncash.api.token=https://sandbox.moncashbutton.digicelgroup.com/Api/oauth/token
moncash.api.payment=https://sandbox.moncashbutton.digicelgroup.com/Api/v1/CreatePayment
moncash.url.redirect=https://sandbox.moncashbutton.digicelgroup.com/IPG/Payment/Pay?token=
